github_token: ENC[AES256_GCM,data:rbwQ2sVhXbLHh31ncWm+nMW1looRsAr1asRRPx60CEvxtdVyLpsBWw==,iv:v/i8Pt5Bl2/KcCZCDg6l//+MAz8MqVTyVtiXDBRLRug=,tag:q62OaChQEs4BROYItYVi2A==,type:str]
db_password: ENC[AES256_GCM,data:l04YgA==,iv:FY329G4TKURNOBoIyX9Y7LJAPIEIU0FJm60b/f3rzfA=,tag:609O2medK8zHTE64KQcEEA==,type:str]
jenkins_client_id: ENC[AES256_GCM,data:z+6Wdw==,iv:SGX3rWp+Xqb3VoXGblB1+RQDSs8Fbq3tQMunjTt8vmo=,tag:RaKl/siFJZ2srGdPH9DnWg==,type:str]
jenkins_client_secret: ENC[AES256_GCM,data:8RMgOg==,iv:YfW/kJqeKj5B1fzthFSnqpPgmzDPvuaFtfMHjrS8A5k=,tag:QrR3ALQztwIMMZRn94uf3g==,type:str]
sightengine_api_user: ENC[AES256_GCM,data:1M56T6s+SRNp,iv:Bg67w58Ppn7Va7u25UCYq/Pjogzl/FJRLA+XyKQ6Dro=,tag:K8RCz0EJIxvTK3BrqAdmlA==,type:int]
sightengine_api_secret: ENC[AES256_GCM,data:QNVy15JJdw8mC+vd7T2G49fHFQxasP9FGjr7tfVCEXU=,iv:quQ38fXCtp3iLYh2InDUmQthsQ4f/HjTKBs4NXI85gg=,tag:3GLbwhUwCo3JRhq2z8nHdg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:633309913072:alias/ainews-sops
          created_at: "2026-02-04T04:22:52Z"
          enc: AQICAHhrWGAxdTVpb4FyGqqnUYgll9AW0G6NZDO6asQjQI4bSAFwiJr/2I2AHV/y2wUaiR3dAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpSVsyZQYi6TfPKv9AgEQgDt9RQq0nmLlVpd1zOH3e4ZrmaU2+MZhHQlIL5pioxUWWHRVGeBqPaz1FF9ksi64xYpmLfCnR9+7T0ge8g==
          aws_profile: ""
    lastmodified: "2026-02-06T08:05:02Z"
    mac: ENC[AES256_GCM,data:IaHz4/pjwZyIKdsmIE4Dh9zViPhEO0vkD+X7KYYnXQ+MSDnnS7E/lc+cILijZI96dfewPpuwm+U9ShisPBtDl6G23dcYDMFe7QXZRbUiiftcrcTyMGKIIxH4kP/2qkpQd6pMeXAcs3P7uES/lnA/DjWXl+XGyY1RwQt0wgVQzKg=,iv:78tgT7FTlQq0My7cCM/bYB/hATuGNnzPRhYZbj5dYxc=,tag:c8ZcVPj1tBtZLdSHWI4I7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
