github_token: ENC[AES256_GCM,data:rbwQ2sVhXbLHh31ncWm+nMW1looRsAr1asRRPx60CEvxtdVyLpsBWw==,iv:v/i8Pt5Bl2/KcCZCDg6l//+MAz8MqVTyVtiXDBRLRug=,tag:q62OaChQEs4BROYItYVi2A==,type:str]
db_password: ENC[AES256_GCM,data:l04YgA==,iv:FY329G4TKURNOBoIyX9Y7LJAPIEIU0FJm60b/f3rzfA=,tag:609O2medK8zHTE64KQcEEA==,type:str]
jenkins_client_id: ENC[AES256_GCM,data:z+6Wdw==,iv:SGX3rWp+Xqb3VoXGblB1+RQDSs8Fbq3tQMunjTt8vmo=,tag:RaKl/siFJZ2srGdPH9DnWg==,type:str]
jenkins_client_secret: ENC[AES256_GCM,data:l7WIbw==,iv:09U5VSD3/9TUlDBmJ0MwGaHu1OYrMELE0lpuQEK/D9c=,tag:JWSYKV4UMoPoEWbnqjw8hA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:633309913072:alias/ainews-sops
          created_at: "2026-02-04T04:22:52Z"
          enc: AQICAHhrWGAxdTVpb4FyGqqnUYgll9AW0G6NZDO6asQjQI4bSAFwiJr/2I2AHV/y2wUaiR3dAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpSVsyZQYi6TfPKv9AgEQgDt9RQq0nmLlVpd1zOH3e4ZrmaU2+MZhHQlIL5pioxUWWHRVGeBqPaz1FF9ksi64xYpmLfCnR9+7T0ge8g==
          aws_profile: ""
    lastmodified: "2026-02-04T04:22:52Z"
    mac: ENC[AES256_GCM,data:LSmphawgjx0pUkxOlLHe6qk9p/LSblfhC/6DRPm7io/UTqJY4GpyhnJFG6zcmUEqIgbxhtBCV6AJFpXBRB3Y2JxAc2g9NWnd9KCq5+qJux3yvlwZPnMWPKnTmQXdhUYGx0m2m4OlSEAgYBLzKkCRZkGYf9GgXWoqRiEKhJGH01Y=,iv:8GzjwfB5hTZs/JNEKOmlGFKtSOgz60eqhbx8fH9cGbI=,tag:G0Lesf1JlQ5RbWQ3KJcRKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
